version: '3.8'

services:
    redis:
      image: redis:7.2-alpine
      container_name: ai-support-redis
      restart: unless-stopped
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      networks:
        - ai-support-network
    backend-email-service:
      image: backend-email-service
      build: .
      container_name: backend-email-service
      restart: unless-stopped
      ports:
        - "8003:8003"
      environment:
        - AI_SERVICE_URL=${AI_SERVICE_URL}
        - DATABASE_SERVICE_URL=${DATABASE_SERVICE_URL}
        - REDIS_URL=redis://redis:6379
        - EMAIL_SERVER=${EMAIL_SERVER}
        - EMAIL_USER=${EMAIL_USER}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - SERVICE_NAME=backend-email-service
        - SERVICE_PORT=8003
      networks:
      - ai-support-network

volumes:
  redis_data:

networks:
  ai-support-network:
    driver: bridge
