version: '3.8'

services:
    redis:
      image: redis:7.2-alpine
      container_name: ai-support-redis
      restart: unless-stopped
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      networks:
        - ai-support-network
    backend-email-service:
      image: backend-email-service
      build: 
        context: ..
        dockerfile: backend-email-service/Dockerfile
      container_name: backend-email-service
      restart: unless-stopped
      ports:
        - "8003:8003"
      env_file:
        - ../.env
        - .env
      environment:
        - REDIS_URL=redis://redis:6379
        - SERVICE_NAME=backend-email-service
        - SERVICE_PORT=8003
      networks:
      - ai-support-network

volumes:
  redis_data:

networks:
  ai-support-network:
    driver: bridge
