version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ai-support-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ai_support
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai-support-network

  backend-database-service:
    build: .
    image: backend-database-service
    container_name: backend-database-service
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/ai_support?authSource=admin
      - SERVICE_NAME=backend-database-service
      - SERVICE_PORT=8001
      - DUPLICATE_SIMILARITY_THRESHOLD=0.7
      - DUPLICATE_TIME_WINDOW_DAYS=7
    depends_on:
      - mongodb
    networks:
      - ai-support-network

volumes:
  mongodb_data:

networks:
  ai-support-network:
    driver: bridge
